<?php
$typeArr[1] = '关于我们';
$typeArr[2] = '成鱼展览';
$typeArr[3] = '鲤鱼';
$typeArr[4] = '鲫鱼';
$typeArr[5] = '草鱼';
$typeArr[7] = '鱼苗展览';
$typeArr[8] = '鲤鱼';
$typeArr[9] = '鲫鱼';
$typeArr[10] = '联系我们';
$typeArr[11] = '首页幻灯';
$typeArr[12] = '资质荣誉';
$typeArr[13] = '科普知识';
$typeArr[14] = '人才招聘';
$typeArr[15] = '留言反馈';
$typeArr[16] = '列表页幻灯';
$typeArr[17] = '手机端首页幻灯';
$typeArr[18] = '手机端地图';
$typeArr[19] = '花鲢';
$typeArr[20] = '白鲢';
?>