<?php
$z[0]=Array("field","",83,112);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","-->\n    {dede:channelartlist  typeid='top' typeid='2' row='6'}\n    <li> <a href=\"{dede:field name=' typeurl'",163,323);
$z[1][4]=array();
$z[1][4]['orderby']="id";
$z[1][4]['titlelen']="80";
$z[1][4]['row']="5";
$z[2]=Array("field","",359,388);
$z[2][4]=array();
$z[2][4]['name']="typeurl";
$z[3]=Array("field","",461,490);
$z[3][4]=array();
$z[3][4]['name']="typename";

?>