-->
<div class="con1"> <p class="p"><span class="iconfontxl">&#xe63f;</span> <span>{dede:field name='typename'/}</span></p>  <br>
  <ul class="con1_list">
    <!--{dede:arclist orderby ='id' titlelen='80' row='5'}-->
    {dede:channelartlist  typeid='top' typeid='2' row='6'}
    <li> <a href="{dede:field name=' typeurl'/}" title="[field:title/]"> <img src="{dede:field name=' typeurl'/}" width="218" height="228" class="PicAuto" alt="[field:title/]" /> <span>{dede:field name='typename'/}</span> <img src="/skin/img/add.png" class="add" /> </a> </li>
    {