<?php
$z[0]=Array("id","",49,60);
$z[0][4]=array();
$z[1]=Array("title","",69,83);
$z[1][4]=array();
$z[2]=Array("litpic","",96,111);
$z[2][4]=array();
$z[3]=Array("title","",118,132);
$z[3][4]=array();
$z[4]=Array("title","",141,155);
$z[4][4]=array();
$z[5]=Array("global","\r\n            \$a=\"<div class='clear'></div>\";\r\n            \$b=\"\";\r\n            if ((@me%2)==0 && @me!=30) @me=\$a;\r\n            else  @me=\$b;\r\n            ",188,399);
$z[5][4]=array();
$z[5][4]['runphp']="yes";
$z[5][4]['name']="autoindex";

?>