<?php
$z[0]=Array("channel","\n           <li><a href=\"list.php?tid=[field:id/]\" class=\"son\">[field:typename/]</a></li>\n          ",222,370);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['row']="4";
$z[1]=Array("arclist","\n      <li> <a href=\"view.php?aid=[field:id/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"><span>[field:title/]</span></a> </li>\n    ",551,743);
$z[1][4]=array();
$z[1][4]['limit']="0,2";
$z[1][4]['orderby']="id";
$z[2]=Array("arclist","\n      <li> <a href=\"view.php?aid=[field:id/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"><span>[field:title/]</span></a> </li>\n    ",797,989);
$z[2][4]=array();
$z[2][4]['limit']="2,2";
$z[2][4]['orderby']="id";

?>