<div class="con1"> <p class="p"><span class="iconfontxl">&#xe63f;</span> <span>{dede:field name='typename'/}</span></p>  <br>
  <ul class="con1_list">
    {dede:arclist  titlelen='80' row='3'}
    <li> <a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" width="218" height="228" class="PicAuto" alt="[field:title/]" /> <span>[field:title/]</span> <img src="/skin/img/add.png" class="add" /> </a> </li>
    {/dede:arclist}
  </ul>
</div>