<?php
$z[0]=Array("field","",73,102);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",138,161);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("field","",287,310);
$z[2][4]=array();
$z[2][4]['name']="id";
$z[3]=Array("sql","[field:content function='cn_substr(html2text(@me),260)'/] ",333,462);
$z[3][4]=array();
$z[3][4]['sql']="Select content from dede_arctype where id=1";

?>