<?php
$z[0]=Array("field","",61,90);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",116,144);
$z[1][4]=array();
$z[1][4]['name']="typeimg";
$z[2]=Array("field","",151,180);
$z[2][4]=array();
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\n    <li>\n      <p><strong>.0[field:global.autoindex/]</strong><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\n      <div>[field:description function=\"cn_substr(@me,160)\"/]...<span>[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span> </div>\n    </li>\n    ",232,585);
$z[3][4]=array();
$z[3][4]['orderby']="id";
$z[3][4]['titlelen']="80";
$z[3][4]['limit']="0,3";
$z[4]=Array("arclist","\n    <li> <img src=\"[field:picname/]\" width=\"166\" height=\"166\"  class=\"PicAuto\" alt=\"[field:title/]\"/> </li>\n    ",623,806);
$z[4][4]=array();
$z[4][4]['orderby']="id";
$z[4][4]['titlelen']="80";
$z[4][4]['limit']="3,3";
$z[5]=Array("field","",883,911);
$z[5][4]=array();
$z[5][4]['name']="typeurl";

?>