<?php
$z[0]=Array("channel","\n           <li><a href=\"list.php?tid=[field:id/]\" class=\"son\">[field:typename/]</a></li>\n          ",311,484);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['typeid']="7";
$z[0][4]['titlelen']="80";
$z[0][4]['row']="4";
$z[1]=Array("field","",573,596);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("channel","\n      <li> <a href=\"list.php?tid=[field:id/]\"><img src=\"[field:typeimg/]\" alt=\"[field:title/]\"><span>[field:typename/]</span></a> </li>\n    ",677,891);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['typeid']="2";
$z[2][4]['titlelen']="80";
$z[2][4]['row']="4";

?>