
<field:name itemname="姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>

<field:phone itemname="手机" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:phone>

<field:email itemname="邮箱" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:email>

<field:content itemname="留言内容" autofield="1" type="multitext" isnull="true" default=""  maxlength="550" page="">
</field:content>

<field:time itemname="提交时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:time>

