<?php
$z[0]=Array("global","",24,49);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",67,82);
$z[1][4]=array();
$z[2]=Array("title","",91,105);
$z[2][4]=array();
$z[3]=Array("title","",107,121);
$z[3][4]=array();
$z[4]=Array("description","",141,191);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,160)";
$z[5]=Array("pubdate","",201,248);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";

?>