<?php
$z[0]=Array("global","",74,96);
$z[0][4]=array();
$z[0][4]['name']="cfg_tel";
$z[1]=Array("global","",98,120);
$z[1][4]=array();
$z[1][4]['name']="cfg_tel";
$z[2]=Array("global","",151,173);
$z[2][4]=array();
$z[2][4]['name']="cfg_fax";
$z[3]=Array("global","",175,197);
$z[3][4]=array();
$z[3][4]['name']="cfg_fax";
$z[4]=Array("field","",230,259);
$z[4][4]=array();
$z[4][4]['name']="typename";
$z[5]=Array("arclist","\n      <li><a href=\"view.php?aid=[field:id/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"><span>[field:title/]</span></a></li>\n    ",319,505);
$z[5][4]=array();
$z[5][4]['row']="2";
$z[5][4]['orderby']="id";

?>