<?php
$z[0]=Array("global","",25,50);
$z[0][4]=array();
$z[0][4]['name']="autoindex";
$z[1]=Array("arcurl","",68,83);
$z[1][4]=array();
$z[2]=Array("title","",92,106);
$z[2][4]=array();
$z[3]=Array("title","",108,122);
$z[3][4]=array();
$z[4]=Array("description","",143,193);
$z[4][4]=array();
$z[4][4]['function']="cn_substr(@me,160)";
$z[5]=Array("pubdate","",203,250);
$z[5][4]=array();
$z[5][4]['function']="MyDate('Y-m-d',@me)";

?>