<?php
$z[0]=Array("field","",102,131);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n        <li><img src=\"[field:picname/]\" /></li>\n        ",216,355);
$z[1][4]=array();
$z[1][4]['orderby']="pubdate";
$z[1][4]['typeid']="12";
$z[1][4]['titlelen']="80";
$z[1][4]['row']="2";
$z[2]=Array("sql","[field:content function='cn_substr(html2text(@me),860)'/] ",564,693);
$z[2][4]=array();
$z[2][4]['sql']="Select content from dede_arctype where id=1";

?>