<?php
$z[0]=Array("field","",43,72);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("field","",106,129);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("arclist","\n        <li><em>.0[field:global.autoindex/]</em> <a href=\"view.php?aid=[field:id/]\">[field:title/]</a>\n<!--          <p>[field:description function=\"cn_substr(@me,100)\"/]...</p>\n -->        </li>\n       ",235,493);
$z[2][4]=array();
$z[2][4]['limit']="0,1";
$z[2][4]['orderby']="id";
$z[3]=Array("arclist","\n        <li><em>.0[field:global name=autoindex runphp=\"yes\"]@me=@me+1;[/field:global]</em><a href=\"view.php?aid=[field:id/]\">[field:title/]</a></li>\n       ",503,714);
$z[3][4]=array();
$z[3][4]['limit']="1,2";
$z[3][4]['orderby']="id";

?>