<?php
$z[0]=Array("channel","\n    <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" width=\"218\" height=\"228\" class=\"PicAuto\" alt=\"[field:title/]\" /> <span>[field:typename/] </span> <img src=\"/skin/img/add.png\" class=\"add\" /> </a> </li>\n    ",0,320);
$z[0][4]=array();
$z[0][4]['orderby']="id";
$z[0][4]['type']="son";
$z[0][4]['titlelen']="80";
$z[0][4]['row']="4";

?>