<?php
$z[0]=Array("channel","\n           <li><a href=\"list.php?tid=[field:id/]\" class=\"son\">[field:typename/]</a></li>\n          ",300,448);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['row']="4";
$z[1]=Array("field","",537,560);
$z[1][4]=array();
$z[1][4]['name']="id";
$z[2]=Array("arclist","\n      <li> <a href=\"view.php?aid=[field:id/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"><span>[field:title/]</span></a> </li>\n    ",641,833);
$z[2][4]=array();
$z[2][4]['limit']="0,2";
$z[2][4]['orderby']="id";
$z[3]=Array("arclist","\n      <li> <a href=\"view.php?aid=[field:id/]\"><img src=\"[field:picname/]\" alt=\"[field:title/]\"><span>[field:title/]</span></a> </li>\n    ",887,1079);
$z[3][4]=array();
$z[3][4]['limit']="2,2";
$z[3][4]['orderby']="id";

?>