<?php
$z[0]=Array("field","",77,106);
$z[0][4]=array();
$z[0][4]['name']="typename";
$z[1]=Array("arclist","\n    <li> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"> <img src=\"[field:picname/]\" width=\"218\" height=\"228\" class=\"PicAuto\" alt=\"[field:title/]\" /> <span>[field:title/]</span> <img src=\"/skin/img/add.png\" class=\"add\" /> </a> </li>\n    ",153,463);
$z[1][4]=array();
$z[1][4]['orderby']="pubdate";
$z[1][4]['titlelen']="80";
$z[1][4]['row']="4";

?>