<div class="con1"> <p><span class="iconfont">&#xe60f;</span> {dede:field name='typename'/}</p>  <br>
  <ul class="con1_list">
    {dede:arclist orderby ='pubdate' titlelen='80' row='4'}
    <li> <a href="[field:arcurl/]" title="[field:title/]"> <img src="[field:picname/]" width="218" height="228" class="PicAuto" alt="[field:title/]" /> <span>[field:title/]</span> <img src="/skin/img/add.png" class="add" /> </a> </li>
    {/dede:arclist}
  </ul>
</div>