<?php
$z[0]=Array("field","",29,57);
$z[0][4]=array();
$z[0][4]['name']="typeimg";
$z[1]=Array("field","",64,93);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("arclist","\r\n    <li>\r\n      <p><strong>.0[field:global.autoindex/]</strong><a href=\"[field:arcurl/]\" title=\"[field:title/]\">[field:title/]</a></p>\r\n      <div>[field:description function=\"cn_substr(@me,160)\"/]...<span>[[field:pubdate function=\"MyDate('Y-m-d',@me)\"/]]</span> </div>\r\n    </li>\r\n    ",143,501);
$z[2][4]=array();
$z[2][4]['orderby']="id";
$z[2][4]['titlelen']="80";
$z[2][4]['limit']="0,3";
$z[3]=Array("arclist","\r\n    <li> <img src=\"[field:picname/]\" width=\"166\" height=\"166\"  class=\"PicAuto\" alt=\"[field:title/]\"/> </li>\r\n    ",542,727);
$z[3][4]=array();
$z[3][4]['orderby']="id";
$z[3][4]['titlelen']="80";
$z[3][4]['limit']="3,3";
$z[4]=Array("field","",805,833);
$z[4][4]=array();
$z[4][4]['name']="typeurl";

?>