<?php
$z[0]=Array("channelartlist"," <span>|</span><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a> ",95,239);
$z[0][4]=array();
$z[0][4]['typeid']="top";
$z[1]=Array("global","",381,407);
$z[1][4]=array();
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",430,452);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",489,511);
$z[3][4]=array();
$z[3][4]['name']="cfg_adr";
$z[4]=Array("global","",591,615);
$z[4][4]=array();
$z[4][4]['name']="cfg_beian";
$z[5]=Array("global","",634,658);
$z[5][4]=array();
$z[5][4]['name']="cfg_beian";

?>