<?php
$z[0]=Array("field","",393,412);
$z[0][4]=array();
$z[0][4]['name']="title";
$z[1]=Array("global","",413,439);
$z[1][4]=array();
$z[1][4]['name']="cfg_webname";
$z[2]=Array("include","",1259,1295);
$z[2][4]=array();
$z[2][4]['filename']="nav_m.htm";
$z[3]=Array("field","",1516,1538);
$z[3][4]=array();
$z[3][4]['name']="typename";
$z[4]=Array("include","",3044,3083);
$z[4][4]=array();
$z[4][4]['filename']="footer_m.htm";

?>