<?php
$z[0]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n		",46,173);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['row']="10";
$z[0][4]['typeid']="2";
$z[1]=Array("channelartlist","\r\n	<div class=\"left_titles iconfont\">&#xe60f;<span>{dede:field.typename/}</span>\r\n		<p>{dede:field name='typenameen'/}</p>\r\n	</div>\r\n	  ",186,378);
$z[1][4]=array();
$z[1][4]['typeid']="7,0";
$z[2]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n		",407,534);
$z[2][4]=array();
$z[2][4]['type']="son";
$z[2][4]['row']="10";
$z[2][4]['typeid']="7";
$z[3]=Array("global","",667,689);
$z[3][4]=array();
$z[3][4]['name']="cfg_adr";
$z[4]=Array("global","",708,730);
$z[4][4]=array();
$z[4][4]['name']="cfg_tel";
$z[5]=Array("global","",749,771);
$z[5][4]=array();
$z[5][4]['name']="cfg_fax";
$z[6]=Array("global","",790,814);
$z[6][4]=array();
$z[6][4]['name']="cfg_email";

?>