<?php
$z[0]=Array("channel","\r\n		<li><a href=\"[field:typeurl/]\">[field:typename/]</a> </li>\r\n		",46,173);
$z[0][4]=array();
$z[0][4]['type']="son";
$z[0][4]['row']="10";
$z[0][4]['typeid']="7";
$z[1]=Array("global","",306,328);
$z[1][4]=array();
$z[1][4]['name']="cfg_adr";
$z[2]=Array("global","",347,369);
$z[2][4]=array();
$z[2][4]['name']="cfg_tel";
$z[3]=Array("global","",388,410);
$z[3][4]=array();
$z[3][4]['name']="cfg_fax";
$z[4]=Array("global","",429,453);
$z[4][4]=array();
$z[4][4]['name']="cfg_email";

?>