<?php
$z[0]=Array("channelartlist","\r\n    <div class=\"left_title iconfont\">&#xe63f;<span>{dede:field name='typename'/}</span>\r\n      <p>{dede:field name='typenameen'/}</p>\r\n    </div>\r\n    ",101,310);
$z[0][4]=array();
$z[0][4]['typeid']="2,0";
$z[1]=Array("field","",368,390);
$z[1][4]=array();
$z[1][4]['name']="typename";
$z[2]=Array("field","",423,452);
$z[2][4]=array();
$z[2][4]['name']="position";

?>